services:
  mysql:
    image: 'mysql:9.1.0'
    environment:
      - 'MYSQL_DATABASE=calculator'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
